//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollectorsAnxiety.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PluginStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PluginStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CollectorsAnxiety.Resources.Localization.PluginStrings", typeof(PluginStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: The Armoire tab will only show items stored within the Armoire. Any items in the Glamour Dresser will not be reflected in the below list..
        /// </summary>
        internal static string ArmoireTab_ArmoireNote {
            get {
                return ResourceManager.GetString("ArmoireTab_ArmoireNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To refresh information and see collection statistics, please visit an Inn Room and open your Armoire. Collector&apos;s Anxiety will automatically refresh this page with the relevant information..
        /// </summary>
        internal static string ArmoireTab_ArmoireNotLoadedError_Message {
            get {
                return ResourceManager.GetString("ArmoireTab_ArmoireNotLoadedError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Armoire is currently not loaded..
        /// </summary>
        internal static string ArmoireTab_ArmoireNotLoadedError_Title {
            get {
                return ResourceManager.GetString("ArmoireTab_ArmoireNotLoadedError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armoire.
        /// </summary>
        internal static string ArmoireTab_Name {
            get {
                return ResourceManager.GetString("ArmoireTab_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barding.
        /// </summary>
        internal static string BuddyEquipTab_Name {
            get {
                return ResourceManager.GetString("BuddyEquipTab_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collector&apos;s Anxiety.
        /// </summary>
        internal static string CollectorsAnxiety_Title {
            get {
                return ResourceManager.GetString("CollectorsAnxiety_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: A player is not logged in. Data may be invalid or incomplete..
        /// </summary>
        internal static string CollectorWindow_NoUserLoggedInWarning {
            get {
                return ResourceManager.GetString("CollectorWindow_NoUserLoggedInWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emotes.
        /// </summary>
        internal static string EmoteTab_Name {
            get {
                return ResourceManager.GetString("EmoteTab_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hairstyles.
        /// </summary>
        internal static string HairstyleTab_Name {
            get {
                return ResourceManager.GetString("HairstyleTab_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:P} Complete ({1} / {2}).
        /// </summary>
        internal static string ImGuiUtil_CompletionProgressBarLabel {
            get {
                return ResourceManager.GetString("ImGuiUtil_CompletionProgressBarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minions.
        /// </summary>
        internal static string MinionTab_Name {
            get {
                return ResourceManager.GetString("MinionTab_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mounts.
        /// </summary>
        internal static string MountTab_Name {
            get {
                return ResourceManager.GetString("MountTab_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orchestrion Rolls.
        /// </summary>
        internal static string OrchestrionTab_Name {
            get {
                return ResourceManager.GetString("OrchestrionTab_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fashion Accessories.
        /// </summary>
        internal static string OrnamentTab_Name {
            get {
                return ResourceManager.GetString("OrnamentTab_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string OverviewTab_Name {
            get {
                return ResourceManager.GetString("OverviewTab_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTab_Name {
            get {
                return ResourceManager.GetString("SettingsTab_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomes.
        /// </summary>
        internal static string TomesTab_Name {
            get {
                return ResourceManager.GetString("TomesTab_Name", resourceCulture);
            }
        }
    }
}
