//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollectorsAnxiety.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CollectorsAnxiety.Resources.Localization.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: The Armoire tab will only show items stored within the Armoire. Any items in the Glamour Dresser will not be reflected in the below list..
        /// </summary>
        internal static string ArmoireTab_ArmoireNote {
            get {
                return ResourceManager.GetString("ArmoireTab_ArmoireNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To refresh information and see collection statistics, please visit an Inn Room and open your Armoire. Collector&apos;s Anxiety will automatically refresh this page with the relevant information..
        /// </summary>
        internal static string ArmoireTab_ArmoireNotLoadedError_Message {
            get {
                return ResourceManager.GetString("ArmoireTab_ArmoireNotLoadedError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Armoire is currently not loaded..
        /// </summary>
        internal static string ArmoireTab_ArmoireNotLoadedError_Title {
            get {
                return ResourceManager.GetString("ArmoireTab_ArmoireNotLoadedError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armoire.
        /// </summary>
        internal static string ArmoireTab_Name {
            get {
                return ResourceManager.GetString("ArmoireTab_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Hidden Only.
        /// </summary>
        internal static string BaseTab_FilterHiddenOnly {
            get {
                return ResourceManager.GetString("BaseTab_FilterHiddenOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All.
        /// </summary>
        internal static string BaseTab_FilterShowAll {
            get {
                return ResourceManager.GetString("BaseTab_FilterShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Complete.
        /// </summary>
        internal static string BaseTab_FilterShowComplete {
            get {
                return ResourceManager.GetString("BaseTab_FilterShowComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Hidden.
        /// </summary>
        internal static string BaseTab_FilterShowHidden {
            get {
                return ResourceManager.GetString("BaseTab_FilterShowHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Incomplete.
        /// </summary>
        internal static string BaseTab_FilterShowIncomplete {
            get {
                return ResourceManager.GetString("BaseTab_FilterShowIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To hide an item from a collection list, right-click the checkbox next to an item and &quot;Hide Item&quot;..
        /// </summary>
        internal static string BaseTab_HiddenHelp {
            get {
                return ResourceManager.GetString("BaseTab_HiddenHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Hidden).
        /// </summary>
        internal static string BaseTab_HiddenTag {
            get {
                return ResourceManager.GetString("BaseTab_HiddenTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Item.
        /// </summary>
        internal static string BaseTab_HideItem {
            get {
                return ResourceManager.GetString("BaseTab_HideItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not yet obtained!.
        /// </summary>
        internal static string BaseTab_SpoilerMask {
            get {
                return ResourceManager.GetString("BaseTab_SpoilerMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barding.
        /// </summary>
        internal static string BuddyEquipTab_Name {
            get {
                return ResourceManager.GetString("BuddyEquipTab_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collector&apos;s Anxiety.
        /// </summary>
        internal static string CollectorsAnxiety_Title {
            get {
                return ResourceManager.GetString("CollectorsAnxiety_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: A player is not logged in. Data may be invalid or incomplete..
        /// </summary>
        internal static string CollectorWindow_NoUserLoggedInWarning {
            get {
                return ResourceManager.GetString("CollectorWindow_NoUserLoggedInWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emotes.
        /// </summary>
        internal static string EmoteTab_Name {
            get {
                return ResourceManager.GetString("EmoteTab_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hairstyles.
        /// </summary>
        internal static string HairstyleTab_Name {
            get {
                return ResourceManager.GetString("HairstyleTab_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:P} Complete ({1} / {2}).
        /// </summary>
        internal static string ImGuiUtil_CompletionProgressBarLabel {
            get {
                return ResourceManager.GetString("ImGuiUtil_CompletionProgressBarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minions.
        /// </summary>
        internal static string MinionTab_Name {
            get {
                return ResourceManager.GetString("MinionTab_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mounts.
        /// </summary>
        internal static string MountTab_Name {
            get {
                return ResourceManager.GetString("MountTab_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orchestrion Rolls.
        /// </summary>
        internal static string OrchestrionTab_Name {
            get {
                return ResourceManager.GetString("OrchestrionTab_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fashion Accessories.
        /// </summary>
        internal static string OrnamentTab_Name {
            get {
                return ResourceManager.GetString("OrnamentTab_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string OverviewTab_Name {
            get {
                return ResourceManager.GetString("OverviewTab_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhide All Items.
        /// </summary>
        internal static string SettingsTab_ClearHiddenItemList {
            get {
                return ResourceManager.GetString("SettingsTab_ClearHiddenItemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        internal static string SettingsTab_Heading_Maintenance {
            get {
                return ResourceManager.GetString("SettingsTab_Heading_Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Options.
        /// </summary>
        internal static string SettingsTab_Heading_SystemOptions {
            get {
                return ResourceManager.GetString("SettingsTab_Heading_SystemOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count Hidden Items in Overview.
        /// </summary>
        internal static string SettingsTab_HiddenItemsInOverview {
            get {
                return ResourceManager.GetString("SettingsTab_HiddenItemsInOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled, the Overview tab will include hidden items in the totals displayed and won&apos;t invalidate your parses. This option does not affect the progress bars on each individual tab..
        /// </summary>
        internal static string SettingsTab_HiddenItemsInOverview_HelpText {
            get {
                return ResourceManager.GetString("SettingsTab_HiddenItemsInOverview_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Translate!.
        /// </summary>
        internal static string SettingsTab_Links_Crowdin {
            get {
                return ResourceManager.GetString("SettingsTab_Links_Crowdin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin GitHub.
        /// </summary>
        internal static string SettingsTab_Links_Github {
            get {
                return ResourceManager.GetString("SettingsTab_Links_Github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTab_Name {
            get {
                return ResourceManager.GetString("SettingsTab_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spoiler-Free Mode.
        /// </summary>
        internal static string SettingsTab_SpoilerFreeMode {
            get {
                return ResourceManager.GetString("SettingsTab_SpoilerFreeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled, this feature will mask all non-collected items with a special icon and spoiler text. Uncollected items will still show in counts. Turning this off may reveal items that are not yet available or otherwise spoil certain experiences..
        /// </summary>
        internal static string SettingsTab_SpoilerFreeMode_HelpText {
            get {
                return ResourceManager.GetString("SettingsTab_SpoilerFreeMode_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomes.
        /// </summary>
        internal static string TomesTab_Name {
            get {
                return ResourceManager.GetString("TomesTab_Name", resourceCulture);
            }
        }
    }
}
